name: Luno
options:
  bundleIdPrefix: com.luno
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5"
    SWIFT_STRICT_CONCURRENCY: targeted
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"

packages:
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "2.2.0"
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: "1.9.0"

targets:
  Luno:
    type: application
    platform: iOS
    sources:
      - path: Luno
        excludes:
          - "**/.DS_Store"
      - path: Luno/Resources/Assets.xcassets
        type: asset
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luno.app
        INFOPLIST_FILE: Luno/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        PRODUCT_NAME: Luno
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Luno/Resources/Luno.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: Luno/Resources/Luno.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.luno.app
        com.apple.developer.icloud-services:
          - CloudDocuments
          - CloudKit
        com.apple.developer.ubiquity-container-identifier:
          - iCloud.com.luno.app
    info:
      path: Luno/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Luno
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UIAppFonts:
          - Syne-Variable.ttf
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSSpeechRecognitionUsageDescription: "Luno uses speech recognition to transcribe your voice notes."
        NSMicrophoneUsageDescription: "Luno needs microphone access to record voice notes."
    dependencies:
      - package: SwiftAnthropic

  LunoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LunoTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luno.app.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luno.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luno"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Luno
      - package: SnapshotTesting

  LunoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LunoUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luno.app.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Luno
    dependencies:
      - target: Luno

schemes:
  Luno:
    build:
      targets:
        Luno: all
        LunoTests: [test]
        LunoUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LunoTests
        - LunoUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
